# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
