# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190428_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
