# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190428_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(default=todo.models.now_plus_10),
        ),
    ]
